### ISSUE TITLE
Writing variables to files.

### ISSUE THREAD

**Issue by JadeSpy** [Olyno/skent#1]
this works: 
append "hello" to file path "plugins/customData/playerStats/%player's uuid%.txt"
this writes <none> in the file
set {_msg} to "hello"
broadcast "%{msg}%"
append "%{msg}%" to file path "plugins/customData/playerStats/%player's uuid%.txt"

**Comment by Olyno** [comment]
Impossible to understand your problem. Please make again your issue and respect the bug format to give me more informations.

I close this issue due to a lot of missing informations to help.
