### ISSUE TITLE
Rename file does not work?

### ISSUE THREAD

**Issue by Misio12320** [Olyno/skent#13]
## Describe your problem

Hi, I'm not sure this is a bug but I suppose so. I have wrote a code to let Skent detect files and rename them to make Minecraft compatible with playsound. The Minecraft does not detect highercase so I replace them via code. The issue is they does not rename because I moved from SkUtilities to Skent and I do not know what I wrote wrong.

## Versions

**Skript:** Skript version 2.5.3
**Server:** This server is running Tuinity version git-Tuinity-"502d57b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Skent:** Skent version 2.1.0

## Code

```vb
command sounds: #3
	trigger:
		set {_name::*} to all files of dir path "plugins/Gods"
		loop {_name::*}:
			set {_t::*} to "%loop-value%"
			set {_t::*} to {_t::*} in lowercase
			set {_t::*} to file name of file path "%{_t::*}%"
			wait 1 real second
			send {_t::*} in lower case
			replace every "_" in {_t::*} with "."
			rename {_t::*} to loop-value
			add "        ""custom.%{_t::*}%"": {" to line {Line1} of file path "sounds/sounds.json"
			add "        ""sounds"": [" to line {Line2} of file path "sounds/sounds.json"
			add "            ""custom/%{_t::*}%""" to line {Line3} of file path "sounds/sounds.json"
			add "        ]" to line {Line4} of file path "sounds/sounds.json"
			add "    }," to line {Line5} of file path "sounds/sounds.json"
			add 5 to {Line1}, {Line2}, {Line3}, {Line4} and {Line5}

on script load: #1
    set {Line1} to 492
    set {Line2} to 493
    set {Line3} to 494
    set {Line4} to 495
    set {Line5} to 496


```

## Error

none.

**Comment by Olyno** [comment]
Well, you can rename 1 or more files at the same time, but it needs to be a ``path``. In your case, you changed the ``path`` type to a ``string`` type (``set {_t::*} to "%loop-value%"``).
If I understood correctly your code, it should be something like:
```vb
command sounds: #3
	trigger:
		set {_name::*} to all files of dir path "plugins/Gods"
		loop {_name::*}:
			set {_name} to file name of file path loop-value in lower case
			replace every "_" in {_name} with "."
			rename loop-value to {_name}
			add "        ""custom.%{_name}%"": {" to line {Line1} of file path "sounds/sounds.json"
			add "        ""sounds"": [" to line {Line2} of file path "sounds/sounds.json"
			add "            ""custom/%{_name}%""" to line {Line3} of file path "sounds/sounds.json"
			add "        ]" to line {Line4} of file path "sounds/sounds.json"
			add "    }," to line {Line5} of file path "sounds/sounds.json"
			add 5 to {Line1}, {Line2}, {Line3}, {Line4} and {Line5}
```

**Comment by Misio12320** [comment]
Thanks for support. I get this message https://pastebin.com/fJnz2eAm and nothing happen.

**Comment by Olyno** [comment]
Hmm seems weird this NullPointerException. I will try to fix it soon as possible, thanks you for the report.

**Comment by Olyno** [comment]
So after a better check I saw that you added a ``without replace`` at the end of the syntax, which should generate you an error because this syntax doesn't exist. Anyway, I think you get a ``NullPointerException`` due to this syntax. Remove ``without replace`` and try again :)

**Comment by Misio12320** [comment]
I have removed: https://pastebin.com/gBsynYfy
`vb
command sounds: #3
	trigger:
		set {_name::*} to all files of dir path "plugins/Gods"
		loop {_name::*}:
			set {_name} to file name of file path loop-value in lower case
			rename loop-value to {_name}
			add "        ""custom.%{_name}%"": {" to line {Line1} of file path "sounds/sounds.json"
			add "        ""sounds"": [" to line {Line2} of file path "sounds/sounds.json"
			add "            ""custom/%{_name}%""" to line {Line3} of file path "sounds/sounds.json"
			add "        ]" to line {Line4} of file path "sounds/sounds.json"
			add "    }," to line {Line5} of file path "sounds/sounds.json"
			add 5 to {Line1}, {Line2}, {Line3}, {Line4} and {Line5}
on script load: #1
    set {Line1} to 492
    set {Line2} to 493
    set {Line3} to 494
    set {Line4} to 495
    set {Line5} to 496`

**Comment by Olyno** [comment]
Plop, here is some news: can you try using a global variable please? If it works fine with a global variable, it means the problem comes directly from Skript (which can't support async stuff yet). If it is not, so....well... it's okay I will find the way to solve it (I guess)

**Comment by Misio12320** [comment]
https://pastebin.com/A7YFjCWZ
code:
```vb
command sounds: #3
	trigger:
		set {name::*} to all files of dir path "plugins/Gods"
		loop {name::*}:
			set {name} to file name of file path loop-value in lower case
			rename loop-value to {name}
			add "        ""custom.%{_name}%"": {" to line {Line1} of file path "sounds/sounds.json"
			add "        ""sounds"": [" to line {Line2} of file path "sounds/sounds.json"
			add "            ""custom/%{_name}%""" to line {Line3} of file path "sounds/sounds.json"
			add "        ]" to line {Line4} of file path "sounds/sounds.json"
			add "    }," to line {Line5} of file path "sounds/sounds.json"
			add 5 to {Line1}, {Line2}, {Line3}, {Line4} and {Line5}```

**Comment by Misio12320** [comment]
So you do not know the solution? May add a non async rename to fix this issue 😞

**Comment by Olyno** [comment]
Well I'm working on it, I just need time

**Comment by Olyno** [comment]
Hi, so here is some news after a long debbugging: this is not a Skent problem. Skript is really bad with async stuff, and local variables are deleted due to that. Please wait a fix from Skript, or a workarround from Skent with some luck.
