### ISSUE TITLE
HTTP requests are running on the main thread, hanging the server

### ISSUE THREAD

**Issue by eDexiam** [Olyno/skent#15]
## Describe your problem

HTTP requests are running on the main thread, hanging the server

## Versions

**Skript:** 2.5.3
**Server:** 1.15.2
**Skent:** 2.1.0

## Error

https://ghostbin.com/paste/rnd3m

**Comment by Olyno** [comment]
Well obviously the expression to get a content from an url is sync, because it's an expression. I'm open to any change we could do to this.

**Comment by eDexiam** [comment]
An effect could be used instead, similar to how Tablisku does it to retrieve skins (https://skripthub.net/docs/?id=3440)
