### ISSUE TITLE
Add no async append

### ISSUE THREAD

**Issue by Misio12320** [Olyno/skent#17]
Add no async append because when I try to use this code
`
on rightclick on any sign:
	if file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt" is missing:
		create file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	else:
		set {_now} to now formatted as "[dd.MM.yyyy HH:mm:ss]"
		set {_loc} to "<x: %x-loc of event-block%; y: %y-loc of event-block%; z: %z-loc of event-block%; świat: %event-block's world%>"
		append "%{_now}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt":
			append "%{_loc}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt":
				set {_1} to line 1 of clicked block
				append "- %{_1}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt":
					set {_2} to line 2 of clicked block
					append "- %{_2}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt":
						set {_3} to line 3 of clicked block
						append "- %{_3}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt":
							set {_4} to line 4 of clicked block
							append "- %{_4}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
` 
it does not work.

https://pastebin.com/pD2Tprhf

**Comment by Olyno** [comment]
Please respect the issue template if you're reporting an issue.
