### ISSUE TITLE
Can't set lines to anything

### ISSUE THREAD

**Issue by EarthAgar** [Olyno/skent#28]
## Describe your problem
I can't use the `set line %number% of %path%` expression

## Versions
**Skript:** 2.5.3 (Also tested on 2.6beta-2)
**Server:** git-Paper-774 (MC: 1.16.5)
**Skent:** 3.0

## Code
```vb
command /line <text>:
	trigger:
		if file path "plugins/Database/test.txt" isn't available:
			create file path "plugins/Database/test.txt":
				broadcast "file created"
				set line 1 of file path "plugins/Database/test.txt" to "%arg 1%"
		else:
			broadcast "file exists"
			set line 1 of file path "plugins/Database/test.txt" to "%arg 1%"
```

## Error
https://paste.helpch.at/osihujupom.md

**Comment by Olyno** [comment]
Fixed in last release
