### ISSUE TITLE
Set lines of file to strings

### ISSUE THREAD

**Issue by PersonMaster** [Olyno/skent#29]
When you set `[all] [the] lines (from|of|in) %path%` to more than one string, it gives an error saying `You cannot set the lines of file "blah" to more than one text...`.

I'd like if you could set it to more than one text, so that you don't have to loop things.

**Comment by Olyno** [comment]
This issue doesn't respect the bug template, i'm closing it. Please take the time to fill the bug template to be able to fix your issue.
