### ISSUE TITLE
Add "output" keyword to "with logs" param when executing a file

### ISSUE THREAD

**Issue by Triblox** [Olyno/skent#30]
## Describe your problem

My py.bat is not executed by the skript command but the game and the game lithener say that it is.

## Versions

**Skript:** 2.6 (``/ver skript``)
**Server:** Paper 1.18.1 (``/ver``)
**Skent:** 3.1.0 (``/ver skent``)

## Code

```vb
command /testbar:
  permission : neon.admin
  trigger:
    set {_files::*} to all files of dir path "python"
    send "Wow Skript has %amount of {_files::*}% files: %{_files::*}%"
    if file path "python/py.bat" is executable file:
      send "vote neon"
    else:
      send "noon"
    execute file path "python/py.bat"
    send "File executed! I'm now a hacker!"

on file execute:
  broadcast "votez neon"
```

```vb
#!/bin/bash

echo "Hello World"
touch test.txt
```

## Error

![image](https://user-images.githubusercontent.com/66395018/152853184-da5e49af-3809-445f-8d07-371586c59adc.png)

**Comment by Olyno** [comment]
Hi 👋🏻 
Thanks you for your report. Actually your code is a ``shell`` code and not a ``bat`` code. Could you retry but using ``execute file path "python/py.sh"`` instead? (and so rename the extension of the file).
Also, because it's shell code and not bat code, it wouldn't work on Windows. Windows can't run shell code without any third party program.

**Comment by Triblox** [comment]
hi ! Do you have discord ? because has you can see in the send message of my list file in the chat i already test it but with the same issue (that nothing append). my discord is _Triblox_#1614 . Tanks for answer so quicly !

**Comment by Olyno** [comment]
There is a discord to support people about Skent, available just [here](https://discord.gg/BbCWeKD)

**Comment by Triblox** [comment]
SOLVED BY : 

change in my skript:
    ``execute file path "python/py.bat"``
to 
    ``execute file path "python/py.sh" with logs``

Clarify by Olyno : 

Just to clarify: the with logs param let you bind the output of any program with the minecraft console, that's why you didn't have the output available
Maybe it could be good to add with output optional, so people can use with output or with logs

The echo will chow with logs :

![image](https://user-images.githubusercontent.com/66395018/152884498-a680fc40-3c48-489b-9e8e-8b6c0814314e.png)

note that the root path is the same that your ./start.sh so i change my py.bat to py.sh (to execute shell) and : 

```vb
#!/bin/bash

echo "Hello World"
touch python/test.txt
```

**Comment by Olyno** [comment]
I reopen the issue but change it to suggestion/new feature, because the developer experience is something important, and the confusion with ``with logs`` can be annoying.

**Comment by Olyno** [comment]
Closing this issue because the keyword is already available.
