### ISSUE TITLE
Can't use local variables with async effects.

### ISSUE THREAD

**Issue by Bonnie20402** [Olyno/skent#37]
## Describe your problem

What's wrong?
Local variables won't work propely in any async effects. The output is always < none >.
E.g creating a file "%{_x}%.json" where {_x} = "name.json" would create a file named "< none >.json"
What is supposed to do?
It should allow me to use local variables on async effects.
The same thing happens if I create a variable in the start and delete at the end of the code.
## Versions

**Skript:** 2.6.2 (Gio's 1.8 fork)
**Server:** Paper 1.8.9
**Skent:** 32.0

## Code

```vb
options:
    mundo_mina:rankup_mina
    mundo_minapvp:rankup_minapvp
    PASTA_DADOS:plugins/BonnieRankup/picaretas


function PickaxeInit(p:player):
    if file path "{@PASTA_DADOS}/%{_p}%.json" is not available:
        async copy file path "plugins/Skript/scripts/rankup/mina/picaretaTemplate.json" to file path "{@PASTA_DADOS}/%{_p}%.json"
        send "&a[PICARETAS] Criamos um ficheiro novo do sistema de picaretas para ti, olha só :) " to {_p}
(..)
```
It created a file named < none >.json

## Error
No error.

**Comment by Olyno** [comment]
This issue should be fixed with the latest version (Skent 3.2.1). Please reopen this issue if you still have this issue.

**Comment by Vulqa** [comment]
I allow myself to reopen the issue, still the same problem on the latest release (3.2.2)

**Comment by Olyno** [comment]
What is your code? @Vulqa?

**Comment by Vulqa** [comment]
```
function copyServer(server: string, template: string):
    async copy file path "/root/minecraft/servers_template/%{_template}%" to file path "/root/minecraft/servers/%{_server}%"
    broadcast "&aServeur &f%{_server}% &a(Template '%{_template}%') copié"

command /test <text> <text>:
    trigger:
        copyServer(arg-1, arg-2)
```

![image](https://github.com/Olyno/skent/assets/41414636/e62d41fc-6acc-467b-8441-a164bd5ee301)

**Comment by Olyno** [comment]
Hi @Vulqa, can you have a look in [this version](https://cdn.discordapp.com/attachments/585898832294838303/1117668537419431996/Skent.jar)? If everything seems good to you, publish it.

**Comment by Olyno** [comment]
Closing this issue as no answer. Please reopen it if you still have this problem.
