### ISSUE TITLE
HTTP Response Code 400 resulting in Skript Severe Error

### ISSUE THREAD

**Issue by Zabrid** [Olyno/skent#38]
## Describe your problem

Basically, occasionally the URL I'm fetching with Skent goes down for a little bit and returns Error Code 400. But I don't think it's necessary for it to write a full severe error message, a little small message maybe just informing you that the website returned that code would be better.

## Versions

**Skript:** 2.6.4 (``/ver skript``)
**Server:** 1.19.3 (``/ver``)
**Skent:** 3.2.2 (``/ver skent``)

## Code

```vb
        sync fetch url "https://api.kyroskoh.xyz/valorant/v1/mmr/%{_region}%/%{_name}%/%{_discriminator}%?show=combo&display=0"
        set {_url} to fetched url content
```

## Error

https://pastebin.com/2p6AyFyK

**Comment by Olyno** [comment]
Hi 👋🏻 Thank you for the report. A 400 http response code means you did a bad request. This is not related to Skent, but related only to your api url. I suppose you're missing an api key. If so, you should give a try to [Reqn](https://github.com/btk5h/reqn)  instead.
