### ISSUE TITLE
on watching file changes   "It ran twice."

### ISSUE THREAD

**Issue by zfms4188** [Olyno/skent#40]
## Versions

**Skript:** 2.6.4 (``/ver skript``)
**Server:** 1.12.2 (``/ver``)
**Skent:** 3.2.2 (6.12) (``/ver skent``)

## Code

```vb
your Skript code here
```
on watching file changes at "plugins/Skript/scripts":
    reload script file file name of event-path
    broadcast "Hello Change"
## Error
"It was executed twice."

**Comment by Olyno** [comment]
Hi 👋🏻
Thank you for the report. I can't reproduce this issue. It is working fine on my side. Feel free to reopen this issue to add more information to this issue, like your OS, Java version and so on.
