### ISSUE TITLE
Copy logs

### ISSUE THREAD

**Issue by VisoXC** [Olyno/skent#42]
I am trying to copy the content of the "latest.log" file in the servers "logs" folder, because it has the servers port, I need. The problem is I can't figure out how it works, because it keeps giving me weird errors, I can't make anything of. 
Could someone give me a code example?

Edit: The content of the "server.properties" file in the main server directory would also work.

**Comment by Olyno** [comment]
Closing this issue as it doesn't rely on the template, missing a lot of information i would need to debug. Please open a new issue following the template.
