### ISSUE TITLE
"Plugins (access denied)"

### ISSUE THREAD

**Issue by VisoXC** [Olyno/skent#44]
## Describe your problem

I was trying to get the "download" feature of skent to work, but it didn't work so I checked the console and it told me that the access to my plugins folder was denied. If the code I wrote was wrong, it would be nice, if you could show me how it's done properly.

## Versions

**Skript:** Skript v2.7.3
**Server:** 1.20.4 (git-Paper-370)
**Skent:** Skent 3.2.2

## Code

```vb
trigger:
    download from "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.21.0-dev+25-fbfd7e9.jar" to dir path "plugins"
```

## Error

https://pastebin.com/3ks3CWrV

**Comment by Olyno** [comment]
Hi,

This error means you don't have access to the ``plugins`` directory. This is probably due to a misconfiguration on your server or something planned if you're using a server provider.

Unfortunately, if you can't fix this permission issue on your side, it means you can't at all.

**Comment by VisoXC** [comment]
Hey,

so you said I don't have permission, to access the plugins folder? Thats weird, because I am hosting the server on my PC and I just loaded a new one, without any plugins or changed settings. But it still doesn't work....

Do you know of a way to fix that, or is it even a problem on my end?

**Comment by Olyno** [comment]
I just found your issue. Skent ``download``'s effect does not work with directories directly. It means, you need to do something like that instead:

```vb
trigger:
    download from "https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.21.0-dev+25-fbfd7e9.jar" to file path "EssentialsX-2.21.0-dev+25-fbfd7e9.jar"
```

This code should work.

**Comment by VisoXC** [comment]
Thanks! That actually fixed the issue :D
