### ISSUE TITLE
if file name

### ISSUE THREAD

**Issue by VisoXC** [Olyno/skent#45]
## Describe your idea
I think there should be a function to do:
```vb
if dir/file name is (not) "<name>":
```
That would make mass handeling files/directories so much easier!

**Comment by Olyno** [comment]
I'm confused, what this syntax should do?

**Comment by VisoXC** [comment]
If you for an example loop all files in a directory, you could filter out specific ones.
```vb
command /test:
    trigger:
        loop all files in dir path "test" or "test2":
            if loop-value's name is "test":
                add loop-value to {_test}
                send "%{_test}%"
```
Or, if you want to reset a plugin, but want to keep a file called "file.dat":
```vb
command /nomorecoolplugin:
    trigger:
        loop all files in dir path "plugins\coolplugin":
            if loop-value's name is not "file.dat":
                delete file path loop-value
```
PS: I didn't check for mistakes in the code.

**Comment by Olyno** [comment]
You can already get the name of a file using this syntax: https://skripthub.net/docs/?id=8081

Remember that if some syntaxes are really specific, it is mainly because it creates conflicts with existing syntaxes in Skript.
