### ISSUE TITLE
Add download file with his name

### ISSUE THREAD

**Issue by Misio12320** [Olyno/skent#5]
Hey. add a feature to download file with his name not with this:
`command download:
	trigger:
		download from url "https://github.com/Olyno/skent/releases/latest/download/skent-all.jar" to file path "plugins/Skent.jar"`
but this:
`command download:
	trigger:
		download from url "https://github.com/Olyno/skent/releases/latest/download/skent-all.jar" to file path "plugins/%name of download file%"`

**Comment by Olyno** [comment]
Something too much of a headache for something insignificant. Adding this feature makes the syntax less flexible. If you want to rename the download file, you can, which is not the case with your syntax.

In conclusion, this syntax will not be added unless it is requested by more Skent users.
