### ISSUE TITLE
Issue with zipping directories

### ISSUE THREAD

**Issue by Nuutrai** [Olyno/skent#54]
## Describe your problem

I'm attempting to zip a directory to a file. I'm running it in Effect Commands since I just want to see how things work (I've just recently switched to Skent) before I add it to the actual skript. Instead of getting a zip though, I get a Severe Error.

## Versions

**Skript:** 2.8.7 
**Server:** 1.20.4 (Paper build 365) 
**Skent:** 3.3.0 

## Code

```vb
-zip dir path "SkLite/TempPrep" to dir path "SkLite/target.zip"
```
(Again, effect command)

## Error

https://pastebin.com/raw/B0k3NXhC

**Comment by Olyno** [comment]
Hi,

Thank you for the report. I will fix this issue asap.

**Comment by Olyno** [comment]
Closing this issue as completed in the Skent version ``3.3.1``.
