### ISSUE TITLE
add "at next line" support

### ISSUE THREAD

**Issue by Misio12320** [Olyno/skent#6]
Hello. Can you dev add a feature to this
```insert "the creator" at line 2 of file path "plugins/Skript/scripts/test1.txt"```
write ```insert "the creator" at NEXT LINE of file path "plugins/Skript/scripts/test1.txt"```
Because I'm trying to move from SkUtilities to Skent and I can't upgrade my codes without this.

**Comment by Govindass** [comment]
there is already append syntax

**Comment by Olyno** [comment]
I didn't understand what you are trying to do, but according to the documentation, you already can:
 * [Append to a file](https://skripthub.net/docs/?id=4222)
 * [Insert to a file](https://skripthub.net/docs/?id=4236)

As these features already exist, your suggestions will not be implemented.

Thanks for your suggestion anyway :smiley:

**Comment by Misio12320** [comment]
> there is already append syntax

Now I see. 


> I didn't understand what you are trying to do, but according to the documentation, you already can:
> 
> * [Append to a file](https://skripthub.net/docs/?id=4222)
> * [Insert to a file](https://skripthub.net/docs/?id=4236)
> 
> As these features already exist, your suggestions will not be implemented.
> 
> Thanks for your suggestion anyway 😃

I think the first link is good, I mean. 
Line 1 has wrote something and I want go to next line write via Skent, seems you sent me correct answer, thanks
